### ISSUE TITLE
TS26.512: M1 Policy Template Provisioning -  Return codes for error handling of put operation

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#104]
## Description
As part of the `PolicyTemplate` object defined in `TS26512_M1_PolicyTemplatesProvisioning.yaml` a `chargingSpecification.sponStatus` of type `TS29514_Npcf_PolicyAuthorization.SponsoringStatus` may be defined. The `SponsoringStatus` string is defined as follow:

````yaml  
SponsoringStatus:
      description: Indicates whether sponsored data connectivity is enabled or disabled/not enabled.
      anyOf:
      - type: string
        enum:
          - SPONSOR_DISABLED
          - SPONSOR_ENABLED
      - type: string
````

Although any value of type `string` is a valid value for this parameter, implementations might only support one of the two possible `enum` values, namely ` SPONSOR_DISABLED` and `SPONSOR_ENABLED`.  In cases in which a value is used that does not correspond to one of the aforementioned `enum` values, it is desirable to send an error code to the sending entity to signal that the request contained unsupported or invalid payload. 

The `put` operation to update an existing policy template defined in `TS26512_M1_PolicyTemplatesProvisioning.yaml` only allows two response codes, namely `204` and `404`. Both are not well suited for the described use case in which an unssuported payload is provided.

## Suggested solution
To handle use cases in which an invalid or unsupported payload is sent as part of the `put` operation, additional response codes should be supported. For instance, a `422` response code allows signaling unprocessable content and might be a good option to signal unsupported parameters in the payload: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

## Related issues
* https://github.com/5G-MAG/rt-5gms-application-function/issues/123
