### ISSUE TITLE
Indentation error in M1_EdgeResourcesProvisioning YAML

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/Standards#38]
_The following bug was detected by Jesús de Gregorio of Ericsson (@jdegre) when checking the TS 26.512 RESTful Media Streaming APIs._

# Description
The following YAML block is incorrect in TS 29.512 V17.2.0 and V17.3.0, clause C.3.9 "M1_EdgeResourcesProvisioning":
```
    EASRequirements:
        type: object
        description: 'Requirements of an EAS.'
        required:
          - easProviderIds
          - easType
          - easFeatures
          - serviceAvailabilitySchedule
          - serviceContinuityScenarios
        properties:
          easProviderIds:
            type: array
              items:
                type: string
``` 

The correct indentation is as follows:
```
    EASRequirements:
        type: object
        description: 'Requirements of an EAS.'
        required:
          - easProviderIds
          - easType
          - easFeatures
          - serviceAvailabilitySchedule
          - serviceContinuityScenarios
        properties:
          easProviderIds:
            type: array
            items:
              type: string
```

# Suggested solution
Raise a CR in the next available 3GPP SA Plenary cycle to correct the YAML in clause C.3.9.

Note that the `EASRequirements` data type is only present from Rel-17 onwards.

# Additional context
The YAML file checked into 3GPP Forge is already correct. This will be retained in 3GPP Forge on the assumption that the paper specification will be corrected at the earliest opportunity.
