### ISSUE TITLE
TS26.512 MetricsReportingConfiguration scheme cardinality does not match YAML definition

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#65]
# Description
TS26.512 V17.4.0 defines the M1 `MetricsReportingConfiguration` resource in table 7.8.3-1. As part of the definition, the cardinality for the `scheme` property is defined as `0..1`. In the corresponding YAML file `TS26512_M1_MetricsReportingProvisioning.yaml` the `scheme` is a required property. 

````yaml
   MetricsReportingConfiguration:
      type: object
      description: "A representation of a Metrics Reporting Configuration resource."
      required:
        - metricsReportingConfigurationId
        - scheme
````

Consequently, the cardinality does not match the YAML definition.

In addition, TS26.512 specifies a scenario in which no `scheme` is provided: _For downlink media streaming, if not specified, the 3GPP metrics scheme urn:3GPP:ns:PSS: DASH:QM10 from TS 26.247 shall apply.
For uplink media streaming, if not specified, the implication is that no associated uplink metrics reporting shall be performed._

# Suggested solution
Clarify whether the `scheme` property is required or not. Looking at TS26.512 this seems to be a minor bug in the corresponding YAML file.
