### ISSUE TITLE
TS26.512 - Typo in word "Metrics" - Should be named "metrics"

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/Standards#67]
# Description
In TS26.512 Table 11.2.3.1-1 _Definition of ServiceAccessInformation resource_ the `Metrics` property in `clientMetricsReporting Configurations` should be written with a lower case "m": `metrics`. Otherwise it does not match the corresponding YAML definition:

````yaml
 metrics:
      type: array
       items:
       type: string
````
